### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by 3kh0** [RCMSUnblockers/rcmsgames#18]
Hello there!

I was just questioning what you are trying to do with my code. You had withdrawn my name from it so I assume you are not trying to develop it. This was code that I got and it could land you in some legal problems if you try and steal it. I am awaiting your response.

Echo

**Comment by webguy24** [comment]
What specific code are you referring to?

**Comment by webguy24** [comment]
Oh, the asteroids game? I believe the person who added that got that from an external website: http://www.dougmcinnes.com/2010/05/12/html-5-asteroids by dmcinnes, which was made in 2016, before your asteroids game. They appear to be quite similar.

**Comment by iamsirsammy** [comment]
Hi, are you referring to Idle Breakout? Removing your name from it was not for a malicious purpose, just a side effect of removing the import code generator to avoid cheating.

Also, you appear to be using the MIT license, so you can only really make us credit you and not make us remove it. I'm adding credit to all copies of this site right now.

**Comment by 3kh0** [comment]
Please ask before adding it, there was no credit on the games before
